# shouldn't be deleting any of these
run_id: 'ep7.31_barajas.v2'
pred_ckpt: ''  # only change if doing inference
resume_ckpt: ''  # leave as '' if not resuming
mdl_key: 'LSTM23'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/test/'
  batch_size: 4096
  val_split: .2

fit:  # shouldn't be deleting any of these
  max_epochs: 1000
  n_nodes: 1
  n_devices: 4
  patience: 1000  # make arbitrarily large to turn off early stopping
  ckpt_freq: 100  # dumb checkpointing: saves every n epochs

model:  # should match the model you are using
  indim: 15
  outdim: 13
  num_layers: 12
  neurons: 128
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  l2: .000001
  dropout: 0.01
  activation: 'relu'
  optimizer: 'adam'


