# shouldn't be deleting any of these
run_id: 'ep7.31_barajas.v3'
pred_ckpt: ''  # only change if doing inference
resume_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/ckpts/ep7.31_barajas.v3/epoch=499-step=42500.ckpt'  # leave as '' if not resuming
mdl_key: 'impr_lstm24'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/test/'
  batch_size: 4096
  val_split: .2

fit:  # shouldn't be deleting any of these
  max_epochs: 1000
  n_nodes: 1
  n_devices: 4
  patience: 1000 # make arbitrarily large to turn off early stopping
  ckpt_freq: 100  # dumb checkpointing: saves every n epochs

model:  # should match the model you are using
  indim: 15
  outdim: 13
  num_linears: 2
  neurons_per_hidden: [256, 128] #this should also be an array, but it must divide the num_linears evenly
  input_neurons: 256
  num_lstm_layers: 4 #the number of lstm layers can be changed here
  hidden_state_size: 256 #in the 2023 
  lr: 0.001
  l2: .0000001
  lr_step: 100
  lr_gam: 0.95
  dropout: 0.45
  activation: 'relu'
  penalty: 1
  optimizer: 'adam'
  one_activation: False
  custom_loss: True
  bias: False
