run_id: 'ew724_shobe24v1' 
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/tb_logs/ew724_LSTMshobe24v1/lightning_logs/version_0/checkpoints/epoch=2999-step=150000.ckpt'
resume_ckpt: ''  
mdl_key: 'LSTM23'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/shobe24v1/train/'
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/shobe24v1/test/'
  batch_size: 2048
  val_split: 0.1

fit:
  max_epochs: 3000
  n_nodes: 1
  n_devices: 4
  patience: 1000
  ckpt_freq: 100

model:
  # LSTM
  indim: 15
  outdim: 13
  num_layers: 16
  neurons: 256
  lr: 0.001
  lr_step: 450
  lr_gam: 0.95
  dropout: 0.25
  activation: 'relu'
  optimizer: 'adam'