# shouldn't be deleting any of these
run_id: 'jh7.24_imprFnn_mship'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/tb_logs/jh7.24_imprFnn_mship/lightning_logs/version_2/checkpoints/epoch=4999-step=455000.ckpt'  # only change if doing inference
resume_ckpt: ''  # leave as '' if not resuming
mdl_key: 'impr_fcn'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/mship_v2/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/mship_v2/test/'
  batch_size: 4096
  val_split: 0.1

fit:  # shouldn't be deleting any of these
  max_epochs: 4000
  n_nodes: 1
  n_devices: 4
  patience:  4000  # make arbitrarily large to turn off early stopping

model:  # should match the model you are using
  input_size: 15
  num_classes: 13 
  hidden_layers: [256, 128, 64, 32, 16]
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  activation: 'relu'
  penalty: 0.00001
  dropout: 0.5