# testing barajas_test
run_id: 'mc7.23_LSTM23v1'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/tb_logs/mc7.23_LSTM23v1/lightning_logs/version_0/checkpoints/epoch=3999-step=1444000.ckpt'  
resume_ckpt: ''  
mdl_key: 'LSTM23'

data:  
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas_test/train/' 
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/test/'
  batch_size: 1024
  val_split: 0.1

fit: 
  max_epochs: 4000
  n_nodes: 1
  n_devices: 4
  patience: 4000 

model: 
  indim: 15
  outdim: 13
  num_layers: 8
  neurons: 256
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  dropout: 0.5
  activation: 'relu'
  optimizer: 'adam'
  