# testing barajas_test with FCN
run_id: 'mc7.23_imFCNv1'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/tb_logs/mc7.23_imFCNv1/lightning_logs/version_0/checkpoints/epoch=4999-step=455000.ckpt'
resume_ckpt: ''
mdl_key: 'impr_fcn'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas_test/train/'  
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas_test/test/'
  batch_size: 2048
  val_split: 0.1

fit:
  max_epochs: 5000
  n_nodes: 1
  n_devices: 8
  patience: 1000

model:
  input_size: 15
  num_classes: 13 
  hidden_layers: [1024, 512, 448, 394, 192, 128, 64, 32, 16]
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  activation: 'relu'
  penalty: 0.0001
  dropout: 0.5
  