# test 0.3
run_id: 'mc7.24_LSTM23v2'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/ckpts/mc7.24_LSTM23v2/epoch=2399-step=674400.ckpt'  # only change if doing inference
resume_ckpt: ''  # leave as '' if not resuming
mdl_key: 'LSTM23'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas_test0.3/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas_test0.3/test/'
  batch_size: 1024
  val_split: 0.1

fit:  # shouldn't be deleting any of these
  max_epochs: 4000
  n_nodes: 1
  n_devices: 4
  patience:  4000  # make arbitrarily large to turn off early stopping
  ckpt_freq: 100

model:  # should match the model you are using
  indim: 15
  outdim: 13
  num_layers: 12
  neurons: 256
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  dropout: 0.7
  activation: 'relu'
  optimizer: 'adam'