# testing very deep fcn, new loss fn, regularization, and checkpointing
run_id: 'mc7.26_imFCNv3'
pred_ckpt: '' 
resume_ckpt: ''
mdl_key: 'impr_fcn'

data:  
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas_test/train/' 
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas_test/test/'
  batch_size: 1024
  val_split: 0.1

fit:  
  max_epochs: 8000
  n_nodes: 1
  n_devices: 4
  patience:  3000 
  ckpt_freq: 100

model:  
  input_size: 15
  num_classes: 13
  hidden_layers: [2048,1024,678,576,512,256,256,256,256,256,256,256,256,64,32,16]
  activation: 'relu'
  lr: 0.005
  lr_step: 500
  lr_gam: 0.95
  penalty: 1
  #dropout: 0.5
  #l2: 0.001

