# naive run on sharma
run_id: 'mc7.30_LSTM23v2'
pred_ckpt: ''
resume_ckpt: ''
mdl_key: 'LSTM23'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/sharma/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/sharma/test/'
  batch_size: 4096
  val_split: 0.1

fit:
  max_epochs: 4000
  n_nodes: 1
  n_devices: 4
  patience: 1000
  ckpt_freq: 500

model:
  # 2023 LSTM
  indim: 15
  outdim: 13
  num_layers: 16
  neurons: 256
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  dropout: 0.5
  l2: 0.0000001  # 1e-7
  #log_test: True
  activation: 'relu'
  optimizer: 'adam'