# FCNv17
run_id: 'mc8.1_imFCNv6'
pred_ckpt: '' 
resume_ckpt: ''
mdl_key: 'impr_fcn'

data:  
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/train/' 
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/test/'
  batch_size: 2048
  val_split: 0.1

fit:  
  max_epochs: 2000
  n_nodes: 1
  n_devices: 4
  patience:  500 
  ckpt_freq: 100

model:  
  input_size: 15
  num_classes: 13
  hidden_layers: [512, 256, 256, 256, 128, 128, 128, 64, 32]
  activation: 'relu'
  lr: 0.0008
  lr_step: 250
  lr_gam: 0.95
  penalty: 1.005
  dropout: 0.1
  l2: 0.01

