# FCNv19
run_id: 'mc8.1_imFCNv8'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/ckpts/mc8.1_imFCNv8/epoch=599-step=57600.ckpt' 
resume_ckpt: ''
mdl_key: 'impr_fcn'

data:  
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/train/' 
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas/test/'
  batch_size: 4096
  val_split: 0.1

fit:  
  max_epochs: 2000
  n_nodes: 1
  n_devices: 4
  patience:  500 
  ckpt_freq: 100

model:  
  input_size: 15
  num_classes: 13
  hidden_layers: [256, 256, 256, 256, 256, 128, 128, 128]
  activation: 'relu'
  lr: 0.001
  lr_step: 250
  lr_gam: 0.95
  penalty: 1.015
  dropout: 0.05
  l2: 0.01

