run_id: 'pjin7.24_mshipv2_ella'
pred_ckpt: ''  # only use if doing inference
resume_ckpt: ''
mdl_key: 'LSTM23'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/mship_v2/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/mship_v2/test/'
  batch_size: 4096
  val_split: 0.2

fit:  # shouldn't be deleting any of these
  max_epochs: 4095
  n_nodes: 1
  n_devices: 4
  patience: 4095

model:
  indim: 15
  outdim: 13
  num_layers: 16
  neurons: 256
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  dropout: 0.15
  activation: 'relu'
  optimizer: 'adam'
