# shouldn't be deleting any of these
run_id: 'ep7.18lstm'
pred_ckpt: ''  # only use if doing inference
mdl_key: 'LSTM23'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/test/'
  batch_size: 4096
  val_split: .25

fit:  # shouldn't be deleting any of these
  max_epochs: 8000
  n_nodes: 1
  n_devices: 4
  patience: 2000 # make arbitrarily large to turn off early stopping

model:  # should match the model you are using
 # 2023 LSTM
  indim: 15
  outdim: 13
  num_layers: 16
  neurons: 256
  momentum: 0.1
