# shouldn't be deleting any of these
run_id: 'ep7.22lstm_ms'
pred_ckpt: ''  # only use if doing inference
mdl_key: 'LSTM23'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/mship_v1/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/mship_v1/test/'
  batch_size: 4096
  val_split: .20

fit:  # shouldn't be deleting any of these
  max_epochs: 8000
  n_nodes: 1
  n_devices: 4
  patience: 2000 # make arbitrarily large to turn off early stopping

model:  # should match the model you are using
 # 2023 LSTM
  indim: 15
  outdim: 13
  num_layers: 24
  neurons: 256
  lr: 0.008
  lr_step: 400
  lr_gam: 0.95
  dropout: 0.5
  activation: 'leakyrelu'
  optimizer: 'adam'
