run_id: 'ew7.23_bplus'
pred_ckpt: ''  # only use if doing inference
resume_ckpt: ''
mdl_key: 'LSTM23'

data:  # shouldn't be deleting any of these
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas+/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas+/test/'
  batch_size: 2048
  val_split: 0.1

fit:  # shouldn't be deleting any of these
  max_epochs: 3000
  n_nodes: 1
  n_devices: 4
  patience: 3000

model:
  indim: 27
  outdim: 13
  num_layers: 16
  neurons: 256
  lr: 0.001
  lr_step: 450
  lr_gam: 0.95
  dropout: 0.25
  activation: 'relu'
  optimizer: 'adam'

