run_id: 'jh.717_lstm.yaml'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/tb_logs/jh.717_lstm.yaml/lightning_logs/version_0/checkpoints/epoch=7999-step=648000.ckpt'
mdl_key: 'LSTM23'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/train/'
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/test/'
  batch_size: 4096
  val_split: 0.2

fit:
  max_epochs: 8000  # changed
  n_nodes: 1
  n_devices: 4
  patience: 2000

model:
  # 2023 LSTM
  indim: 15
  outdim: 13
  num_layers: 16
  neurons: 256
  momentum: 0.1
  # had to add below since code changed
  lr: 0.001
  lr_step: 450
  lr_gam: 0.95
  dropout: 0.25
  activation: 'relu'
  optimizer: 'adam'