run_id: 'mc7.16_imFCNv1'
pred_ckpt: ''
mdl_key: 'impr_fcn'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/gldnboy/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/gldnboy/test/'
  batch_size: 200
  val_split: 0.1

fit:
  max_epochs: 5000
  n_nodes: 2
  n_devices: 4
  patience: 1000

model:
  input_size: 15
  num_classes: 13 
  hidden_layers: [512, 394, 256, 192, 128, 96, 64, 32, 16]
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  activation: 'leakyrelu'
  penalty: 0.1
  dropout: 0.2
  