run_id: 'mc7.16_imFCNv2'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/tb_logs/mc7.16_imFCNv2/lightning_logs/version_1/checkpoints/epoch=2999-step=387000.ckpt'
mdl_key: 'impr_fcn'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/gldnboy/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/gldnboy/test/'
  batch_size: 1000
  val_split: 0.1

fit:
  max_epochs: 3000
  n_nodes: 1
  n_devices: 6
  patience: 1000

model:
  input_size: 15
  num_classes: 13 
  hidden_layers: [512, 394, 256, 192, 128, 96, 64, 32, 16]
  lr: 0.001
  lr_step: 400
  lr_gam: 0.95
  activation: 'leakyrelu'
  penalty: 1.1
  dropout: 0.2
  