run_id: 'mc7.18_LSTM23v1'
pred_ckpt: ''
mdl_key: 'LSTM23'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/gldnboy/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/gldnboy/test/'
  batch_size: 4096
  val_split: 0.2

fit:
  max_epochs: 5000
  n_nodes: 1
  n_devices: 4
  patience: 1000

model:
  # 2023 LSTM
  indim: 15
  outdim: 13
  num_layers: 16
  neurons: 256
  momentum: 0.1