run_id: 'mc7.15_FCNv1'
pred_ckpt: '/nfs/rs/cybertrn/reu2024/team2/base/logs/tb_logs/mc7.15_FCNv1/lightning_logs/version_3/checkpoints/epoch=2999-step=183000.ckpt'

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/test/'
  batch_size: 2048

fit:
  max_epochs: 3000
  
model:
  hidden_units: (256, 128, 64, 32, 16)
  lr: 0.008
  