run_id: 'mc7.15_LSTM23v1'
pred_ckpt: ''

data:
  train_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/train/'  # must include '/' at end
  test_data_path: '/nfs/rs/cybertrn/reu2024/team2/base/pp2/data/barajas24/test/'
  batch_size: 4096

fit:
  max_epochs: 3000
  
model:
  hidden_units: (0,0)
  lr: 0.0
  